import { Schema } from "@/vocabulary/schema";
import { SchemaTextField } from "@/vocabulary/schema/elements";

export const _10fieldSchema: Schema = {
  type: "object",
  properties: {
    field1: { label: "field", layout: { component: "text-field" } },
    field2: { label: "field", layout: { component: "text-field" } },
    field3: { label: "field", layout: { component: "text-field" } },
    field4: { label: "field", layout: { component: "text-field" } },
    field5: { label: "field", layout: { component: "text-field" } },
    field6: { label: "field", layout: { component: "text-field" } },
    field7: { label: "field", layout: { component: "text-field" } },
    field8: { label: "field", layout: { component: "text-field" } },
    field9: { label: "field", layout: { component: "text-field" } },
    field10: { label: "field", layout: { component: "text-field" } },
  },
};

export const _50fieldSchema: Schema = {
  type: "object",
  properties: {
    field1: { label: "field", layout: { component: "text-field" } },
    field2: { label: "field", layout: { component: "text-field" } },
    field3: { label: "field", layout: { component: "text-field" } },
    field4: { label: "field", layout: { component: "text-field" } },
    field5: { label: "field", layout: { component: "text-field" } },
    field6: { label: "field", layout: { component: "text-field" } },
    field7: { label: "field", layout: { component: "text-field" } },
    field8: { label: "field", layout: { component: "text-field" } },
    field9: { label: "field", layout: { component: "text-field" } },
    field10: { label: "field", layout: { component: "text-field" } },
    field11: { label: "field", layout: { component: "text-field" } },
    field12: { label: "field", layout: { component: "text-field" } },
    field13: { label: "field", layout: { component: "text-field" } },
    field14: { label: "field", layout: { component: "text-field" } },
    field15: { label: "field", layout: { component: "text-field" } },
    field16: { label: "field", layout: { component: "text-field" } },
    field17: { label: "field", layout: { component: "text-field" } },
    field18: { label: "field", layout: { component: "text-field" } },
    field19: { label: "field", layout: { component: "text-field" } },
    field20: { label: "field", layout: { component: "text-field" } },
    field21: { label: "field", layout: { component: "text-field" } },
    field22: { label: "field", layout: { component: "text-field" } },
    field23: { label: "field", layout: { component: "text-field" } },
    field24: { label: "field", layout: { component: "text-field" } },
    field25: { label: "field", layout: { component: "text-field" } },
    field26: { label: "field", layout: { component: "text-field" } },
    field27: { label: "field", layout: { component: "text-field" } },
    field28: { label: "field", layout: { component: "text-field" } },
    field29: { label: "field", layout: { component: "text-field" } },
    field30: { label: "field", layout: { component: "text-field" } },
    field31: { label: "field", layout: { component: "text-field" } },
    field32: { label: "field", layout: { component: "text-field" } },
    field33: { label: "field", layout: { component: "text-field" } },
    field34: { label: "field", layout: { component: "text-field" } },
    field35: { label: "field", layout: { component: "text-field" } },
    field36: { label: "field", layout: { component: "text-field" } },
    field37: { label: "field", layout: { component: "text-field" } },
    field38: { label: "field", layout: { component: "text-field" } },
    field39: { label: "field", layout: { component: "text-field" } },
    field40: { label: "field", layout: { component: "text-field" } },
    field41: { label: "field", layout: { component: "text-field" } },
    field42: { label: "field", layout: { component: "text-field" } },
    field43: { label: "field", layout: { component: "text-field" } },
    field44: { label: "field", layout: { component: "text-field" } },
    field45: { label: "field", layout: { component: "text-field" } },
    field46: { label: "field", layout: { component: "text-field" } },
    field47: { label: "field", layout: { component: "text-field" } },
    field48: { label: "field", layout: { component: "text-field" } },
    field49: { label: "field", layout: { component: "text-field" } },
    field50: { label: "field", layout: { component: "text-field" } },
  },
};

export const _100fieldSchema: Schema = {
  type: "object",
  properties: {
    field1: { label: "field", layout: { component: "text-field" } },
    field2: { label: "field", layout: { component: "text-field" } },
    field3: { label: "field", layout: { component: "text-field" } },
    field4: { label: "field", layout: { component: "text-field" } },
    field5: { label: "field", layout: { component: "text-field" } },
    field6: { label: "field", layout: { component: "text-field" } },
    field7: { label: "field", layout: { component: "text-field" } },
    field8: { label: "field", layout: { component: "text-field" } },
    field9: { label: "field", layout: { component: "text-field" } },
    field10: { label: "field", layout: { component: "text-field" } },
    field11: { label: "field", layout: { component: "text-field" } },
    field12: { label: "field", layout: { component: "text-field" } },
    field13: { label: "field", layout: { component: "text-field" } },
    field14: { label: "field", layout: { component: "text-field" } },
    field15: { label: "field", layout: { component: "text-field" } },
    field16: { label: "field", layout: { component: "text-field" } },
    field17: { label: "field", layout: { component: "text-field" } },
    field18: { label: "field", layout: { component: "text-field" } },
    field19: { label: "field", layout: { component: "text-field" } },
    field20: { label: "field", layout: { component: "text-field" } },
    field21: { label: "field", layout: { component: "text-field" } },
    field22: { label: "field", layout: { component: "text-field" } },
    field23: { label: "field", layout: { component: "text-field" } },
    field24: { label: "field", layout: { component: "text-field" } },
    field25: { label: "field", layout: { component: "text-field" } },
    field26: { label: "field", layout: { component: "text-field" } },
    field27: { label: "field", layout: { component: "text-field" } },
    field28: { label: "field", layout: { component: "text-field" } },
    field29: { label: "field", layout: { component: "text-field" } },
    field30: { label: "field", layout: { component: "text-field" } },
    field31: { label: "field", layout: { component: "text-field" } },
    field32: { label: "field", layout: { component: "text-field" } },
    field33: { label: "field", layout: { component: "text-field" } },
    field34: { label: "field", layout: { component: "text-field" } },
    field35: { label: "field", layout: { component: "text-field" } },
    field36: { label: "field", layout: { component: "text-field" } },
    field37: { label: "field", layout: { component: "text-field" } },
    field38: { label: "field", layout: { component: "text-field" } },
    field39: { label: "field", layout: { component: "text-field" } },
    field40: { label: "field", layout: { component: "text-field" } },
    field41: { label: "field", layout: { component: "text-field" } },
    field42: { label: "field", layout: { component: "text-field" } },
    field43: { label: "field", layout: { component: "text-field" } },
    field44: { label: "field", layout: { component: "text-field" } },
    field45: { label: "field", layout: { component: "text-field" } },
    field46: { label: "field", layout: { component: "text-field" } },
    field47: { label: "field", layout: { component: "text-field" } },
    field48: { label: "field", layout: { component: "text-field" } },
    field49: { label: "field", layout: { component: "text-field" } },
    field50: { label: "field", layout: { component: "text-field" } },
    field51: { label: "field", layout: { component: "text-field" } },
    field52: { label: "field", layout: { component: "text-field" } },
    field53: { label: "field", layout: { component: "text-field" } },
    field54: { label: "field", layout: { component: "text-field" } },
    field55: { label: "field", layout: { component: "text-field" } },
    field56: { label: "field", layout: { component: "text-field" } },
    field57: { label: "field", layout: { component: "text-field" } },
    field58: { label: "field", layout: { component: "text-field" } },
    field59: { label: "field", layout: { component: "text-field" } },
    field60: { label: "field", layout: { component: "text-field" } },
    field61: { label: "field", layout: { component: "text-field" } },
    field62: { label: "field", layout: { component: "text-field" } },
    field63: { label: "field", layout: { component: "text-field" } },
    field64: { label: "field", layout: { component: "text-field" } },
    field65: { label: "field", layout: { component: "text-field" } },
    field66: { label: "field", layout: { component: "text-field" } },
    field67: { label: "field", layout: { component: "text-field" } },
    field68: { label: "field", layout: { component: "text-field" } },
    field69: { label: "field", layout: { component: "text-field" } },
    field70: { label: "field", layout: { component: "text-field" } },
    field71: { label: "field", layout: { component: "text-field" } },
    field72: { label: "field", layout: { component: "text-field" } },
    field73: { label: "field", layout: { component: "text-field" } },
    field74: { label: "field", layout: { component: "text-field" } },
    field75: { label: "field", layout: { component: "text-field" } },
    field76: { label: "field", layout: { component: "text-field" } },
    field77: { label: "field", layout: { component: "text-field" } },
    field78: { label: "field", layout: { component: "text-field" } },
    field79: { label: "field", layout: { component: "text-field" } },
    field80: { label: "field", layout: { component: "text-field" } },
    field81: { label: "field", layout: { component: "text-field" } },
    field82: { label: "field", layout: { component: "text-field" } },
    field83: { label: "field", layout: { component: "text-field" } },
    field84: { label: "field", layout: { component: "text-field" } },
    field85: { label: "field", layout: { component: "text-field" } },
    field86: { label: "field", layout: { component: "text-field" } },
    field87: { label: "field", layout: { component: "text-field" } },
    field88: { label: "field", layout: { component: "text-field" } },
    field89: { label: "field", layout: { component: "text-field" } },
    field90: { label: "field", layout: { component: "text-field" } },
    field91: { label: "field", layout: { component: "text-field" } },
    field92: { label: "field", layout: { component: "text-field" } },
    field93: { label: "field", layout: { component: "text-field" } },
    field94: { label: "field", layout: { component: "text-field" } },
    field95: { label: "field", layout: { component: "text-field" } },
    field96: { label: "field", layout: { component: "text-field" } },
    field97: { label: "field", layout: { component: "text-field" } },
    field98: { label: "field", layout: { component: "text-field" } },
    field99: { label: "field", layout: { component: "text-field" } },
    field100: { label: "field", layout: { component: "text-field" } },
  },
};

export const invoicePositionsSchema: Schema = {
  type: "object",
  properties: {
    invoiceItems: {
      layout: {
        component: "duplicated-section",
        items: {
          product: {
            label: "Product",
            layout: { component: "text-field", cols: 3 },
          },
          quantity: {
            label: "Quantity",
            layout: { component: "text-field", cols: 1 },
            type: "number",
          },
          netPrice: {
            label: "Net price",
            layout: { component: "text-field", cols: 2 },
          },
          tax: { label: "Tax", layout: { component: "text-field", cols: 3 } },
          summary: {
            label: "Summary",
            layout: { component: "text-field", cols: 3 },
            calculation: "quantity * (netPrice+netPrice*tax)",
          } as SchemaTextField,
        },
        options: {
          addBtnText: { $ref: "#/i18n/~$locale~/addAction" },
          showDivider: true,
        },
      },
    },
  },
  i18n: {
    en: {
      addAction: "Add row",
    },
    pl: {
      addAction: "Dodaj wiersz",
    },
  },
};
