printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
htmlWhitespaceSensitivity: ignore
endOfLine: lf
singleAttributePerLine: true
