FROM nginx:stable-alpine

# Create directory for Storybook
RUN mkdir -p /usr/share/nginx/html/storybook

# Copy Storybook files
COPY storybook-static/ /usr/share/nginx/html/storybook/

# Copy custom nginx config
COPY nginx-storybook.conf /etc/nginx/nginx.conf
