const MOCK_OFFER_ITEMS_RESPONSE = {
  content: [
    {
      dataId: "d598bcd7-c98d-4704-bdc6-4320044540e5",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "b7a10f25-7526-475a-981c-f133543421b8",
        number: "KR0139-MET-LY1903",
        name: "Chairs 2 pcs TUMKUR",
        status: "OFFER",
        programName: "CHAIRS",
        mainImage: {
          id: "L2ltcG9ydGVkL3Byb2R1Y3RzL2tyemVzJUM1JTgyYV8yMDIxLTA5LTAyXzExMzA0MS9LUjAxMzktTUVULUxZMTkwM18wNi5qcGc=",
          dataId: "b7a10f25-7526-475a-981c-f133543421b8",
          name: "KR0139-MET-LY1903_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: 0.77,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: -0.77,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: null,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 0.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
      ],
    },
    {
      dataId: "3ba78ebc-4bd7-4f0a-b220-c12a0da91e2c",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "b673fc28-8981-4df7-97a6-9d16017f0d35",
        number: "KR0139-MET-Y676",
        name: "Chairs 2 pcs TUMKUR",
        status: "OFFER",
        programName: "CHAIRS",
        mainImage: {
          id: "L19kZWZhdWx0X3VwbG9hZF9idWNrZXQvS1IwMTM5LU1FVC1ZNjc2XzA2LmpwZw==",
          dataId: "b673fc28-8981-4df7-97a6-9d16017f0d35",
          name: "KR0139-MET-Y676_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: 0.77,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: -0.77,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: null,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 0.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
      ],
    },
    {
      dataId: "cc1eaf8c-7e75-483c-be56-e8298f3bd26b",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "114981bc-4602-43de-a2df-f4071908a96f",
        number: "KR0128-B99-ONR91",
        name: "Chairs 2 pcs VEGALTA",
        status: "OFFER",
        programName: "CHAIRS",
        mainImage: {
          id: "L2ltcG9ydGVkL3Byb2R1Y3RzL2tyemVzJUM1JTgyYV8yMDIxLTA5LTAyXzExMzA0MS9LUjAxMjgtQjk5LU9OUjkxXzA2LmpwZw==",
          dataId: "114981bc-4602-43de-a2df-f4071908a96f",
          name: "KR0128-B99-ONR91_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: 0.72,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: -0.72,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: null,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 0.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
      ],
    },
    {
      dataId: "018c1bfb-82d4-4522-8adc-bf10b01f379d",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "2fb0f989-f8f7-4d74-bd82-3675e342672a",
        number: "KR0140-MET-Y016",
        name: "Chairs 2 pcs YADGIR",
        status: "OFFER",
        programName: "CHAIRS",
        mainImage: {
          id: "L19kZWZhdWx0X3VwbG9hZF9idWNrZXQvS1IwMTQwLU1FVC1ZMDE2XzA2LmpwZw==",
          dataId: "2fb0f989-f8f7-4d74-bd82-3675e342672a",
          name: "KR0140-MET-Y016_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: 0.66,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: -0.66,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: null,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 0.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
      ],
    },
    {
      dataId: "46172056-5813-49e5-83f3-4effd9efb10d",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "cfb1a8b0-f5e4-485a-82e5-5d8102ad3046",
        number: "FSGK233B-M395",
        name: "Chest",
        status: null,
        programName: "FIRST LEAGUE",
        mainImage: {
          id: "L19kZWZhdWx0X3VwbG9hZF9idWNrZXQvRlNHSzIzM0ItTTM5NV8wNi5qcGc=",
          dataId: "cfb1a8b0-f5e4-485a-82e5-5d8102ad3046",
          name: "FSGK233B-M395_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: null,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: null,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: null,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 0.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
        {
          type: "warning",
          message: "unknown product volume, cannot calculate transport cost",
        },
      ],
    },
    {
      dataId: "3faacbf3-ac73-4dc7-a6a7-a963c5367f36",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "a1856746-6171-4a44-8b13-fe3a91cd855b",
        number: "KR0096-D47-LAT1",
        name: "Set 2 chairs",
        status: "OFFER",
        programName: "CHAIRS",
        mainImage: {
          id: "L2ltcG9ydGVkL3Byb2R1Y3RzL2tyemVzJUM1JTgyYV8yMDIxLTA5LTAyXzExMzA0MS9LUjAwOTYtRDQ3LUxBVDFfMDYuanBn",
          dataId: "a1856746-6171-4a44-8b13-fe3a91cd855b",
          name: "KR0096-D47-LAT1_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: 0.9,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: -0.9,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: 123312321,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 1231323.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
      ],
    },
    {
      dataId: "3d4aaec7-cfec-4b82-965f-92d7bf697d29",
      palletQuantity: null,
      palletQuantityIcon: null,
      invoicePrice: 0.0,
      factoryCost: null,
      retailPriceFactor: 1.0,
      targetRetailPriceGross: null,
      product: {
        id: "f61512fa-7c71-4898-86d4-3ff52c966d33",
        number: "KR0112-MET-YBS07",
        name: "Set.2chairs.metal.chr/dbl.stitching Grey",
        status: "OFFER",
        programName: "CHAIRS",
        mainImage: {
          id: "L2ltcG9ydGVkL3Byb2R1Y3RzL2tyemVzJUM1JTgyYV8yMDIxLTA5LTAyXzExMzA0MS9LUjAxMTItTUVULVlCUzA3XzA2LmpwZw==",
          dataId: "f61512fa-7c71-4898-86d4-3ff52c966d33",
          name: "KR0112-MET-YBS07_06.jpg",
          lastModifiedAt: null,
        },
      },
      details: {
        transportCost: 0.46,
        otherCost: 2.0,
        currentPrice: null,
        nnnPrice: 0.0,
        nnnExwPrice: -0.46,
        minimalInvoicePrice: null,
        minimalMarginPercent: 15.0,
        minimalNnnPrice: null,
        minimalNnnExwPrice: null,
        recommendedInvoicePrice: null,
        recommendedMarginPercent: 25.0,
        recommendedNnnPrice: null,
        recommendedNnnExwPrice: null,
        retailPriceNet: 0.0,
        retailPriceGross: 0.0,
        marginPercent: 0.0,
        customerMarginPercent: 0.0,
        retailPriceFactor: 1.0,
        currencyCode: "EUR",
      },
      alerts: [
        {
          type: "warning",
          message: "no package quantity defined for product, using one package for calculations",
        },
      ],
    },
  ],
  page: {
    size: 10,
    number: 0,
    totalElements: 7,
    totalPages: 1,
  },
};
export const OFFER_ITEMS_MOCK = {
  url: "/api/v1/offers/maciek-offer/offer-items?page=0&size=10",
  method: "GET",
  status: 200,
  response: (request) => {
    const { body, searchParams } = request;

    return MOCK_OFFER_ITEMS_RESPONSE;
  },
};

const MOCK_RELATIONSHIP_RESPONSE = {
  content: [
    {
      dataId: "8a6a5f37-c2fe-4319-b3f1-fbb72e33320b_WE",
      partner: {
        id: "8a6a5f37-c2fe-4319-b3f1-fbb72e33320b",
        name: "TUCO VALENCIA  EL OSITO",
        number: "794201",
      },
      function: {
        id: "WE",
        name: "Ship To Party",
      },
    },
    {
      dataId: "d6231bf6-bf77-4250-bac2-5bb07d2b3582_AG",
      partner: {
        id: "d6231bf6-bf77-4250-bac2-5bb07d2b3582",
        name: "MOBELMUR 2020 S.L.U.",
        number: "7942",
      },
      function: {
        id: "AG",
        name: "Sold To Party",
      },
    },
    {
      dataId: "d6231bf6-bf77-4250-bac2-5bb07d2b3582_RE",
      partner: {
        id: "d6231bf6-bf77-4250-bac2-5bb07d2b3582",
        name: "MOBELMUR 2020 S.L.U.",
        number: "7942",
      },
      function: {
        id: "RE",
        name: "Bill To Party",
      },
    },
    {
      dataId: "d6231bf6-bf77-4250-bac2-5bb07d2b3582_RG",
      partner: {
        id: "d6231bf6-bf77-4250-bac2-5bb07d2b3582",
        name: "MOBELMUR 2020 S.L.U.",
        number: "7942",
      },
      function: {
        id: "RG",
        name: "Payer",
      },
    },
    {
      dataId: "d6231bf6-bf77-4250-bac2-5bb07d2b3582_WE",
      partner: {
        id: "d6231bf6-bf77-4250-bac2-5bb07d2b3582",
        name: "MOBELMUR 2020 S.L.U.",
        number: "7942",
      },
      function: {
        id: "WE",
        name: "Ship To Party",
      },
    },
    {
      dataId: "eb4159fb-fa30-4771-af17-5a8920ed134f_WE",
      partner: {
        id: "eb4159fb-fa30-4771-af17-5a8920ed134f",
        name: "TUCO CASTELLÓN (SALERA)",
        number: "794202",
      },
      function: {
        id: "WE",
        name: "Ship To Party",
      },
    },
  ],
  page: {
    size: 10,
    number: 0,
    totalElements: 6,
    totalPages: 1,
  },
};
export const RELATIONSHIP_RESPONSE = {
  url: "/api/v1/customers/1/relationships?page=0&size=10",
  method: "GET",
  status: 200,
  response: (request) => {
    const { body, searchParams } = request;

    return MOCK_RELATIONSHIP_RESPONSE;
  },
};
